apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml -o k8s-manifests/
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: worker
  name: worker
  namespace: ledgerforge
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: worker
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml -o k8s-manifests/
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: worker
    spec:
      containers:
        - command:
            - ledgerforge
            - workers
            - --config
            - /ledgerforge.json
          env:
            - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
              value: http://jaeger:4318/v1/traces
          image: ghcr.io/devaccuracy/ledgerforge:main
          name: worker
          ports:
            - containerPort: 5004
          resources: {}
          volumeMounts:
            - name: ledgerforge-config
              mountPath: /ledgerforge.json
              subPath: ledgerforge.json
      restartPolicy: Always
      volumes:
        - name: ledgerforge-config
          configMap:
            name: ledgerforge-config
